version: "3.9"
services:
  postgres-db:
    container_name: appDatabase
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - ./appdata/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
  app:
    container_name: application
    image: app
    restart: unless-stopped
    depends_on:
      - postgres-db
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USERNAME=${POSTGRES_DB_USERNAME}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}

  nginx:
    image: nginx:1.23.1
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data/www:/data/www
    ports:
      - 80:80